spring:
  application:
    name: franquicias
  r2dbc:
    url: r2dbc:mysql://localhost:3306/franquicias
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:admin}
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
